// AUTOGENERATED by src/tools/build-symbols.mjs — DO NOT EDIT.
// Source: QElectroTech elements library (CC-BY 3.0 by The QElectroTech team).
// See NOTICE.md for attribution. Run `npm run build:symbols` to regenerate.

import type { SymbolDef } from './types';

export const SYMBOL_REGISTRY: readonly SymbolDef[] = [
  {
    id: "breaker",
    label: "Circuit breaker",
    category: "switchgear",
    voltageTier: "hv",
    displaySize: {"width":32,"height":64},
    body: {"width":32,"height":48},
    bodyViewBox: {"x":3,"y":27,"width":16,"height":23},
    terminals: [{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100},{"id":"terminal-top","side":"top","xPct":50,"yPct":0}],
    defaultData: {"tag":"Q","ratedVoltage":245,"ratedCurrent":3150},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"ratedCurrent","label":"Rated current","type":"number","unit":"A"},{"key":"breakingCapacity","label":"Breaking cap.","type":"number","unit":"kA/1s"},{"key":"interruptingMedium","label":"Medium","type":"select","options":["SF6","vacuum","oil","air"]}],
    svgBody: `
  <line x1="11" y1="50" x2="3" y2="27" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="9" y1="28" x2="13" y2="32" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="13" y1="28" x2="9" y2="32" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "disconnector",
    label: "Disconnector",
    category: "switchgear",
    voltageTier: "hv",
    displaySize: {"width":32,"height":64},
    body: {"width":32,"height":48},
    bodyViewBox: {"x":3,"y":27,"width":16,"height":23},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"QS","ratedVoltage":245,"ratedCurrent":3150},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"ratedCurrent","label":"Rated current","type":"number","unit":"A"},{"key":"motorised","label":"Motorised","type":"select","options":["yes","no"]}],
    svgBody: `
  <line x1="11" y1="50" x2="3" y2="27" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="8" y1="30" x2="14" y2="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "earthing-switch",
    label: "Earthing switch",
    category: "switchgear",
    voltageTier: "hv",
    displaySize: {"width":32,"height":56},
    body: {"width":32,"height":48},
    bodyViewBox: {"x":2,"y":18,"width":20,"height":32},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0}],
    defaultData: {"tag":"QE","ratedVoltage":245},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"shortCircuitMaking","label":"Making cap.","type":"number","unit":"kA"}],
    svgBody: `
  <line x1="9" y1="18" x2="15" y2="18" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="12" y1="18" x2="4" y2="36" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="2" y1="40" x2="22" y2="40" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="5" y1="45" x2="19" y2="45" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="8" y1="50" x2="16" y2="50" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "surge-arrester",
    label: "Surge arrester",
    category: "switchgear",
    voltageTier: "hv",
    displaySize: {"width":32,"height":64},
    body: {"width":32,"height":48},
    bodyViewBox: {"x":4,"y":20,"width":12,"height":20},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"FV","ratedVoltage":198},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"dischargeCurrent","label":"Nom. discharge","type":"number","unit":"kA"},{"key":"energyClass","label":"Energy class","type":"select","options":["1","2","3","4","5"]}],
    svgBody: `
  <rect x="4" y="20" width="12" height="20" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="6" y1="24" x2="14" y2="36" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "transformer",
    label: "Two-winding transformer",
    category: "transformers",
    voltageTier: "hv",
    displaySize: {"width":48,"height":96},
    body: {"width":48,"height":80},
    bodyViewBox: {"x":26,"y":42,"width":60,"height":100},
    terminals: [{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100},{"id":"terminal-top","side":"top","xPct":50,"yPct":0}],
    defaultData: {"tag":"T","ratedPower":250,"primaryVoltage":220,"secondaryVoltage":110,"vectorGroup":"YNyn0"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedPower","label":"Rated power","type":"number","unit":"MVA"},{"key":"primaryVoltage","label":"Primary","type":"number","unit":"kV"},{"key":"secondaryVoltage","label":"Secondary","type":"number","unit":"kV"},{"key":"vectorGroup","label":"Vector group","type":"text"},{"key":"cooling","label":"Cooling","type":"select","options":["ONAN","ONAF","OFAF","ODAF"]}],
    svgBody: `
  <ellipse cx="56" cy="72" rx="30" ry="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <ellipse cx="56" cy="112" rx="30" ry="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "transformer-3w",
    label: "Three-winding transformer",
    category: "transformers",
    voltageTier: "hv",
    displaySize: {"width":48,"height":64},
    body: {"width":48,"height":48},
    bodyViewBox: {"x":2,"y":10,"width":60,"height":57},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":0,"yPct":100},{"id":"terminal-bottom-2","side":"bottom","xPct":100,"yPct":100}],
    defaultData: {"tag":"T","ratedPower":450,"primaryVoltage":400,"secondaryVoltage":220,"tertiaryVoltage":30,"vectorGroup":"YNautod11"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedPower","label":"Rated power","type":"number","unit":"MVA"},{"key":"primaryVoltage","label":"Primary (HV)","type":"number","unit":"kV"},{"key":"secondaryVoltage","label":"Secondary (MV)","type":"number","unit":"kV"},{"key":"tertiaryVoltage","label":"Tertiary (LV)","type":"number","unit":"kV"},{"key":"vectorGroup","label":"Vector group","type":"text"}],
    svgBody: `
  <ellipse cx="32" cy="25" rx="15" ry="15" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <ellipse cx="17" cy="52" rx="15" ry="15" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <ellipse cx="47" cy="52" rx="15" ry="15" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "ct",
    label: "Current transformer",
    category: "measurement",
    voltageTier: "hv",
    displaySize: {"width":32,"height":48},
    body: {"width":32,"height":32},
    bodyViewBox: {"x":3,"y":21,"width":18,"height":18},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"TI","ratio":"1000/5","accuracyClass":"0.2S"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratio","label":"Ratio","type":"text"},{"key":"accuracyClass","label":"Accuracy","type":"select","options":["0.1","0.2","0.2S","0.5","0.5S","1","5P","10P","TPX","TPY","TPZ"]},{"key":"burden","label":"Burden","type":"number","unit":"VA"},{"key":"cores","label":"Cores","type":"number"}],
    svgBody: `
  <ellipse cx="12" cy="30" rx="9" ry="9" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "vt",
    label: "Voltage transformer (inductive)",
    category: "measurement",
    voltageTier: "hv",
    displaySize: {"width":32,"height":80},
    body: {"width":32,"height":64},
    bodyViewBox: {"x":2,"y":14,"width":26,"height":52},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"TV","ratio":"110000:√3 / 100:√3","accuracyClass":"0.2"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratio","label":"Ratio","type":"text"},{"key":"accuracyClass","label":"Accuracy","type":"select","options":["0.1","0.2","0.5","1","3","3P","6P"]},{"key":"burden","label":"Burden","type":"number","unit":"VA"}],
    svgBody: `
  <ellipse cx="15" cy="27" rx="13" ry="13" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <ellipse cx="15" cy="53" rx="13" ry="13" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "cvt",
    label: "Capacitor voltage transformer",
    category: "measurement",
    voltageTier: "hv",
    displaySize: {"width":32,"height":80},
    body: {"width":32,"height":64},
    bodyViewBox: {"x":3,"y":14,"width":18,"height":39},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"TV","ratio":"220000:√3 / 100:√3","accuracyClass":"0.5"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratio","label":"Ratio","type":"text"},{"key":"accuracyClass","label":"Accuracy","type":"select","options":["0.1","0.2","0.5","1","3","3P","6P"]},{"key":"burden","label":"Burden","type":"number","unit":"VA"},{"key":"totalCapacitance","label":"C1+C2","type":"number","unit":"nF"}],
    svgBody: `
  <line x1="4" y1="14" x2="20" y2="14" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="4" y1="18" x2="20" y2="18" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="12" y1="18" x2="12" y2="26" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="4" y1="26" x2="20" y2="26" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="4" y1="30" x2="20" y2="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="12" y1="30" x2="12" y2="35" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <ellipse cx="12" cy="44" rx="9" ry="9" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "protection-relay",
    label: "Protection relay",
    category: "protection",
    voltageTier: "hv",
    displaySize: {"width":32,"height":48},
    body: {"width":32,"height":32},
    bodyViewBox: {"x":4,"y":12,"width":32,"height":32},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":25,"yPct":100,"kind":"control"},{"id":"terminal-bottom-2","side":"bottom","xPct":75,"yPct":100,"kind":"control"}],
    defaultData: {"tag":"F","functionCode":"50/51"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"functionCode","label":"ANSI function","type":"text"},{"key":"pickupCurrent","label":"Pickup","type":"number","unit":"A"},{"key":"timeDial","label":"Time dial","type":"number"}],
    svgBody: `
  <rect x="4" y="12" width="32" height="32" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <text x="20" y="28" text-anchor="middle" dominant-baseline="central" fill="currentColor" stroke="none" font-family="var(--font-mono, monospace)" font-size="14" font-weight="600">I></text>
`,
  },
  {
    id: "generator",
    label: "Generator",
    category: "sources-loads",
    voltageTier: "hv",
    displaySize: {"width":48,"height":48},
    body: {"width":48,"height":48},
    bodyViewBox: {"x":5,"y":5,"width":60,"height":60},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"G","ratedPower":300,"ratedVoltage":21,"powerFactor":0.85},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedPower","label":"Rated power","type":"number","unit":"MVA"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"powerFactor","label":"Power factor","type":"number"},{"key":"machineType","label":"Type","type":"select","options":["synchronous","asynchronous"]}],
    svgBody: `
  <polygon points="32,38 33,36 32,34 34,34 35,32 36,34 38,34 37,36 38,38 35,37" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="currentColor"/>
  <ellipse cx="35" cy="35" rx="30" ry="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <text x="35" y="35" text-anchor="middle" dominant-baseline="central" fill="currentColor" stroke="none" font-family="var(--font-mono, monospace)" font-size="14" font-weight="600">G</text>
`,
  },
  {
    id: "motor",
    label: "Motor",
    category: "sources-loads",
    voltageTier: "mv",
    displaySize: {"width":48,"height":48},
    body: {"width":48,"height":48},
    bodyViewBox: {"x":5,"y":5,"width":60,"height":60},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"M","ratedPower":1500,"ratedVoltage":6000},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedPower","label":"Rated power","type":"number","unit":"kW"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"V"},{"key":"speedRpm","label":"Speed","type":"number","unit":"rpm"}],
    svgBody: `
  <polygon points="32,38 33,36 32,34 34,34 35,32 36,34 38,34 37,36 38,38 35,37" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="currentColor"/>
  <ellipse cx="35" cy="35" rx="30" ry="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <text x="35" y="35" text-anchor="middle" dominant-baseline="central" fill="currentColor" stroke="none" font-family="var(--font-mono, monospace)" font-size="14" font-weight="600">M</text>
`,
  },
  {
    id: "ground",
    label: "Ground",
    category: "sources-loads",
    voltageTier: "lv",
    displaySize: {"width":32,"height":40},
    body: {"width":32,"height":32},
    bodyViewBox: {"x":5,"y":22,"width":20,"height":15},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0}],
    defaultData: {"tag":"PE"},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"}],
    svgBody: `
  <line x1="5" y1="22" x2="25" y2="22" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="8" y1="27" x2="22" y2="27" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="11" y1="32" x2="19" y2="32" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="15.5" y1="37" x2="14.5" y2="37" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "shunt-reactor",
    label: "Shunt reactor",
    category: "compensation",
    voltageTier: "hv",
    displaySize: {"width":32,"height":80},
    body: {"width":32,"height":64},
    bodyViewBox: {"x":3,"y":16,"width":14,"height":28},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"LR","ratedPower":100,"ratedVoltage":420},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"ratedPower","label":"Rated power","type":"number","unit":"MVAr"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"cooling","label":"Cooling","type":"select","options":["ONAN","ONAF","dry"]}],
    svgBody: `
  <rect x="3" y="16" width="14" height="28" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="3" y1="23" x2="17" y2="23" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="3" y1="30" x2="17" y2="30" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="3" y1="37" x2="17" y2="37" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
  {
    id: "shunt-capacitor",
    label: "Shunt capacitor bank",
    category: "compensation",
    voltageTier: "hv",
    displaySize: {"width":32,"height":32},
    body: {"width":32,"height":16},
    bodyViewBox: {"x":1,"y":17,"width":18,"height":6},
    terminals: [{"id":"terminal-top","side":"top","xPct":50,"yPct":0},{"id":"terminal-bottom","side":"bottom","xPct":50,"yPct":100}],
    defaultData: {"tag":"CB","reactivePower":50,"ratedVoltage":36},
    propertySchema: [{"key":"tag","label":"Tag","type":"text"},{"key":"reactivePower","label":"Reactive power","type":"number","unit":"MVAr"},{"key":"ratedVoltage","label":"Rated voltage","type":"number","unit":"kV"},{"key":"configuration","label":"Connection","type":"select","options":["Y-grounded","Y-ungrounded","double-Y","delta"]}],
    svgBody: `
  <line x1="1" y1="17" x2="19" y2="17" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
  <line x1="1" y1="23" x2="19" y2="23" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
`,
  },
];
